// クエリ名: q_預り書_倉庫リスト
// 預り書に登場する倉庫名の一覧（重複なし）。出力対象を絞り込むために使う。
//
// 型式が空で集計対象外になった行でも、倉庫名そのものは
// 「預り書に存在する倉庫」として扱う。
// （型式が空なだけで倉庫ごと結果から消えてしまうのを防ぐため）
//
// 結果はテーブルではなくリストになる。
let
    非空 = Table.SelectRows(q_預り書_明細, each [倉庫名] <> "")
in
    List.Distinct(非空[倉庫名])
